/*
 * Personal cryptographic algorithm
 * This cipher converts the input text (supports English, Georgian, emojis) into a square grid,
 * prepends a random salt to expand and randomize the message, then pulses the grid by
 * rotating rows and columns by key-derived shifts.
 *
 * The encrypted output is generated by reading the grid diagonally, enhancing diffusion and confusion.
 * Decryption reverses the process using the same key, restoring the original message.
 */

const NULL_CHAR = "\u0000";

const TEST_CASES_FOR_PERSONAL_ALGORITHM = [
  {
    text: "გამარჯობა",
    key: "საიდუმლოო",
  },
  {
    text: "ტესტი",
    key: "რაიმე",
  },
  {
    text: "Hello World",
    key: "secret",
  },
  {
    text: "Hello World",
    key: "გასაღები",
  },
];

function toGrid(chars = [], size = 0) {
  const grid = [];
  let index = 0;
  for (let row = 0; row < size; row++) {
    const r = [];
    for (let col = 0; col < size; col++) {
      r.push(chars[index] || NULL_CHAR);
      index++;
    }
    grid.push(r);
  }
  return grid;
}

function fromGrid(grid = []) {
  return grid.flat().join("").replace(new RegExp(NULL_CHAR, "g"), "");
}

function diagonalRead(grid = []) {
  const size = grid.length;
  let result = "";
  for (let sum = 0; sum <= 2 * (size - 1); sum++) {
    for (let i = 0; i <= sum; i++) {
      const row = i;
      const col = sum - i;
      if (row < size && col < size) {
        result += grid[row][col];
      }
    }
  }
  return result;
}

function diagonalWrite(text = "", size = 0) {
  const grid = Array.from({ length: size }, () => Array(size).fill(NULL_CHAR));
  let index = 0;
  for (let sum = 0; sum <= 2 * (size - 1); sum++) {
    for (let i = 0; i <= sum; i++) {
      const row = i;
      const col = sum - i;
      if (row < size && col < size) {
        grid[row][col] = text[index++] || NULL_CHAR;
      }
    }
  }
  return grid;
}

function keyShift(key = "", index = 0) {
  const charCode = key.charCodeAt(index % key.length);
  return (charCode + index) % 10;
}

function rotateRight(arr = [], n = 0) {
  n = n % arr.length;
  return arr.slice(-n).concat(arr.slice(0, -n));
}

function rotateLeft(arr = [], n = 0) {
  n = n % arr.length;
  return arr.slice(n).concat(arr.slice(0, n));
}

function pulseGrid(grid = [], key = "") {
  const size = grid.length;

  for (let i = 0; i < size; i++) {
    const shift = keyShift(key, i);
    grid[i] = rotateRight(grid[i], shift);
  }

  for (let col = 0; col < size; col++) {
    const shift = keyShift(key, col + size);
    const column = grid.map((row) => row[col]);
    const rotated = rotateRight(column, shift);
    for (let row = 0; row < size; row++) {
      grid[row][col] = rotated[row];
    }
  }

  return grid;
}

function unpulseGrid(grid = [], key = "") {
  const size = grid.length;

  for (let col = 0; col < size; col++) {
    const shift = keyShift(key, col + size);
    const column = grid.map((row) => row[col]);
    const rotated = rotateLeft(column, shift);
    for (let row = 0; row < size; row++) {
      grid[row][col] = rotated[row];
    }
  }

  for (let i = 0; i < size; i++) {
    const shift = keyShift(key, i);
    grid[i] = rotateLeft(grid[i], shift);
  }

  return grid;
}

function generateSalt(length = 5) {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  let salt = "";
  for (let i = 0; i < length; i++) {
    salt += chars[Math.floor(Math.random() * chars.length)];
  }
  return salt;
}

function personalEncrypt(text = "", key = "") {
  if (typeof text !== "string" || typeof key !== "string") {
    throw new Error("Both text and key must be strings");
  }

  if (text.length === 0 || key.length === 0) {
    throw new Error("Text and key cannot be empty");
  }

  const salt = generateSalt(5);
  const payload = salt + text;

  const chars = Array.from(payload);
  const size = Math.ceil(Math.sqrt(chars.length));

  const grid = toGrid(chars, size);
  const pulsed = pulseGrid(grid, key);
  const encryptedText = diagonalRead(pulsed);

  return encryptedText;
}

function personalDecrypt(encryptedText = "", key = "") {
  if (typeof encryptedText !== "string" || typeof key !== "string") {
    throw new Error("Both encrypted text and key must be strings");
  }

  if (encryptedText.length === 0 || key.length === 0) {
    throw new Error("Encrypted text and key cannot be empty");
  }

  const size = Math.ceil(Math.sqrt(encryptedText.length));
  const diagGrid = diagonalWrite(encryptedText, size);

  const unpulsed = unpulseGrid(diagGrid, key);
  const full = fromGrid(unpulsed);

  const decryptedText = full.slice(5);
  return decryptedText;
}

function personalMain(cases = TEST_CASES_FOR_PERSONAL_ALGORITHM) {
  console.log("==================================================");
  if (cases.length === 0) {
    console.warn("No test cases provided");
    return;
  }
  console.info(`Personal Cipher Test Cases (${cases.length} test)\n`);
  cases.forEach(({ text, key }) => {
    try {
      console.info(`Original: ${text}`);
      console.info(`Key: ${key}`);
      const encryptedText = personalEncrypt(text, key);
      console.info(`Encrypted: ${encryptedText}`);

      const decryptedText = personalDecrypt(encryptedText, key);
      console.info(`Decrypted: ${decryptedText}`);

      if (decryptedText !== text) {
        throw new Error(
          "Decryption failed: decrypted text does not match original"
        );
      }

      console.info(`Decryption successful, encryption matches decryption.\n`);
    } catch (error) {
      console.error(`Error: ${error.message}\n`);
    }
  });
  console.log("==================================================");
}

personalMain(TEST_CASES_FOR_PERSONAL_ALGORITHM);
